### ISSUE TITLE
Add support for elasticsearch 5.3.0

### ISSUE THREAD

**Issue by g-stawarczyk** [antqa/elasticsearch-analysis-morfologik#2]
Hey, can you add support for elasticsearch 5.3.0?

**Comment by piotrantosik** [comment]
Hey,

I will try to release at the weekend.

**Comment by piotrantosik** [comment]
Sorry for delay - pls test and get info if work properly - https://github.com/antqa/elasticsearch-analysis-morfologik/releases/tag/5.3.0
